### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mawansui** [SeonghwanSeo/PharmacoNet#1]
Hello. I was impressed by your arxiv pre-print. Great job! I opened this issue to say thank you for your work and for releasing the code. I am looking forward to the release of the Molvoxel library as well, as I would like to try your tool some day soon. From what I understood, at the moment the code cannot be launched without it. Many thanks again, have a nice day!

**Comment by SeonghwanSeo** [comment]
Hi, thank you for your interest.
We are currently in the process of usability testing the MolVoxel library and plan to release it in November!

**Comment by SeonghwanSeo** [comment]
The MolVoxel is released.
