### ISSUE TITLE
a small problem with quotations 

### ISSUE THREAD

**Issue by yordan-ov** [SeonghwanSeo/PharmacoNet#2]
First i want to congratulate you on the great tool. 

I noticed a small error with quotations when trying to run the provided examples. It runs fine if i don't put the input chemical in quotations.  Provided the details below:

 E:\programs\PharmacoNet>python scoring.py -p ./examples/6OIM_model.json -s 'c1ccccc1' --num_conformers 8
==============================
*** Open Babel Error  in OpenBabel::OBSmilesParser::ParseSimple
  SMILES string contains a character ''' which is invalid
Traceback (most recent call last):
  File "E:\programs\PharmacoNet\scoring.py", line 43, in <module>
    score = scoring(args.smiles, model, args.num_conformers)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\programs\PharmacoNet\scoring.py", line 21, in scoring
    pbmol = pybel.readstring('smi', smiles)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\Programs\conda\envs\pmnet\Lib\openbabel\pybel.py", line 209, in readstring
    raise IOError("Failed to convert '%s' to format '%s'" % (
OSError: Failed to convert ''c1ccccc1'' to format 'smi'

**Comment by SeonghwanSeo** [comment]
Hello @yordan-ov,
Thanks for letting me know. I am currently only running it on LINUX and MAC environments and have not checked its behavior on WINDOW environments, so I am not aware of this issue. I will add documents on different OS environments in the future.
